"""Flask web application for serving A.U.R.O.R.A. orchestrator generated files.

This module provides a web interface to view and serve files generated by the
aurora_orchestrator. It dynamically serves frontend files from the PROJECT_STATE
codebase without requiring them to be written to disk.
"""
from __future__ import annotations

import json
import os
from flask import Flask, jsonify, render_template_string, Response
from typing import Dict, Optional

# Import aurora_orchestrator components
from aurora_orchestrator import (
    AuroraOrchestrator,
    PROJECT_STATE,
    CONFIG,
    SimulationSettings,
    persist_final_state,
)


app = Flask(__name__)
app.config['JSON_SORT_KEYS'] = False


# HTML template for the main dashboard
DASHBOARD_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>A.U.R.O.R.A. Orchestrator Dashboard</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh;
            padding: 20px;
        }
        .container {
            max-width: 1400px;
            margin: 0 auto;
        }
        .header {
            background: white;
            padding: 30px;
            border-radius: 12px;
            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
            margin-bottom: 30px;
        }
        h1 {
            color: #2d3748;
            font-size: 2.5em;
            margin-bottom: 10px;
        }
        .project-info {
            color: #718096;
            font-size: 1.1em;
        }
        .stats-grid {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
            gap: 20px;
            margin-bottom: 30px;
        }
        .stat-card {
            background: white;
            padding: 25px;
            border-radius: 12px;
            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
        }
        .stat-number {
            font-size: 3em;
            font-weight: bold;
            color: #667eea;
            margin-bottom: 10px;
        }
        .stat-label {
            color: #718096;
            font-size: 1.1em;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        .section {
            background: white;
            padding: 30px;
            border-radius: 12px;
            box-shadow: 0 8px 32px rgba(0, 0, 0, 0.1);
            margin-bottom: 30px;
        }
        .section h2 {
            color: #2d3748;
            margin-bottom: 20px;
            font-size: 1.8em;
        }
        .file-list {
            list-style: none;
        }
        .file-item {
            padding: 15px;
            border-bottom: 1px solid #e2e8f0;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        .file-item:last-child {
            border-bottom: none;
        }
        .file-path {
            color: #4a5568;
            font-family: 'Monaco', 'Courier New', monospace;
            font-size: 0.95em;
        }
        .file-action {
            background: #667eea;
            color: white;
            padding: 8px 16px;
            border-radius: 6px;
            text-decoration: none;
            transition: background 0.3s;
        }
        .file-action:hover {
            background: #5568d3;
        }
        .message-item {
            padding: 15px;
            background: #f7fafc;
            border-left: 4px solid #667eea;
            margin-bottom: 10px;
            border-radius: 4px;
        }
        .message-agent {
            font-weight: bold;
            color: #667eea;
            margin-bottom: 5px;
        }
        .message-text {
            color: #4a5568;
        }
        .design-system {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
            gap: 20px;
        }
        .design-card {
            padding: 20px;
            background: #f7fafc;
            border-radius: 8px;
        }
        .design-card h3 {
            color: #2d3748;
            margin-bottom: 15px;
        }
        .color-swatch {
            display: inline-block;
            width: 60px;
            height: 60px;
            border-radius: 8px;
            margin-right: 10px;
            border: 2px solid #e2e8f0;
        }
        .empty-state {
            text-align: center;
            color: #a0aec0;
            padding: 40px;
            font-style: italic;
        }
        .btn {
            display: inline-block;
            background: #667eea;
            color: white;
            padding: 12px 24px;
            border-radius: 6px;
            text-decoration: none;
            transition: background 0.3s;
            margin-top: 10px;
        }
        .btn:hover {
            background: #5568d3;
        }
        .last-update {
            color: #718096;
            font-size: 0.9em;
            margin-top: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🚀 A.U.R.O.R.A. Orchestrator Dashboard</h1>
            <p class="project-info">
                Project: <strong>{{ config.project_name }}</strong> | 
                Domain: <strong>{{ config.domain_name }}</strong> | 
                Tech Stack: <strong>{{ config.code_language }} + {{ config.frontend_framework }}</strong>
            </p>
            {% if last_update %}
            <p class="last-update">Last Update: {{ last_update }}</p>
            {% endif %}
        </div>

        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-number">{{ stats.completed }}</div>
                <div class="stat-label">Tasks Completed</div>
            </div>
            <div class="stat-card">
                <div class="stat-number">{{ stats.files }}</div>
                <div class="stat-label">Files Generated</div>
            </div>
            <div class="stat-card">
                <div class="stat-number">{{ stats.messages }}</div>
                <div class="stat-label">Messages Posted</div>
            </div>
            <div class="stat-card">
                <div class="stat-number">{{ stats.in_progress }}</div>
                <div class="stat-label">In Progress</div>
            </div>
        </div>

        <div class="section">
            <h2>📁 Generated Files</h2>
            {% if files %}
            <ul class="file-list">
                {% for path in files %}
                <li class="file-item">
                    <span class="file-path">{{ path }}</span>
                    <a href="/files/{{ path }}" class="file-action">View</a>
                </li>
                {% endfor %}
            </ul>
            {% else %}
            <div class="empty-state">No files generated yet. Run the orchestrator to generate files.</div>
            {% endif %}
        </div>

        <div class="section">
            <h2>🎨 Design System</h2>
            <div class="design-system">
                {% if design_system.colors %}
                <div class="design-card">
                    <h3>Colors</h3>
                    {% for name, color in design_system.colors.items() %}
                    <div style="margin-bottom: 10px;">
                        <span class="color-swatch" style="background-color: {{ color }}"></span>
                        <strong>{{ name }}:</strong> {{ color }}
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
                {% if design_system.typography %}
                <div class="design-card">
                    <h3>Typography</h3>
                    {% for key, value in design_system.typography.items() %}
                    <p><strong>{{ key }}:</strong> {{ value }}</p>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
            {% if not design_system.colors and not design_system.typography %}
            <div class="empty-state">Design system not yet defined.</div>
            {% endif %}
        </div>

        <div class="section">
            <h2>💬 Message Bus</h2>
            {% if messages %}
            <div>
                {% for message in messages %}
                <div class="message-item">
                    <div class="message-text">{{ message }}</div>
                </div>
                {% endfor %}
            </div>
            {% else %}
            <div class="empty-state">No messages on the bus yet.</div>
            {% endif %}
        </div>

        <div class="section">
            <h2>📊 API Endpoints</h2>
            <ul class="file-list">
                <li class="file-item">
                    <span class="file-path">/api/state</span>
                    <a href="/api/state" class="file-action">View JSON</a>
                </li>
                <li class="file-item">
                    <span class="file-path">/api/files</span>
                    <a href="/api/files" class="file-action">View JSON</a>
                </li>
            </ul>
        </div>
    </div>
</body>
</html>
"""

# File viewer template
FILE_VIEWER_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ file_path }} - A.U.R.O.R.A.</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
            background: #f7fafc;
            padding: 20px;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
        }
        .header {
            background: white;
            padding: 20px 30px;
            border-radius: 12px;
            box-shadow: 0 4px 16px rgba(0, 0, 0, 0.1);
            margin-bottom: 20px;
            display: flex;
            justify-content: space-between;
            align-items: center;
        }
        h1 {
            color: #2d3748;
            font-size: 1.5em;
            font-family: 'Monaco', 'Courier New', monospace;
        }
        .back-btn {
            background: #667eea;
            color: white;
            padding: 10px 20px;
            border-radius: 6px;
            text-decoration: none;
            transition: background 0.3s;
        }
        .back-btn:hover {
            background: #5568d3;
        }
        .content {
            background: white;
            padding: 30px;
            border-radius: 12px;
            box-shadow: 0 4px 16px rgba(0, 0, 0, 0.1);
        }
        pre {
            background: #2d3748;
            color: #e2e8f0;
            padding: 20px;
            border-radius: 8px;
            overflow-x: auto;
            line-height: 1.6;
            font-family: 'Monaco', 'Courier New', monospace;
            font-size: 0.95em;
        }
        code {
            font-family: 'Monaco', 'Courier New', monospace;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{{ file_path }}</h1>
            <a href="/" class="back-btn">← Back to Dashboard</a>
        </div>
        <div class="content">
            <pre><code>{{ content }}</code></pre>
        </div>
    </div>
</body>
</html>
"""


@app.route('/')
def dashboard():
    """Render the main dashboard showing project state and generated files."""
    stats = {
        'completed': len(PROJECT_STATE['tasks']['completed']),
        'in_progress': len(PROJECT_STATE['tasks']['in_progress']),
        'files': len(PROJECT_STATE['codebase']['files']),
        'messages': len(PROJECT_STATE['message_bus']),
    }
    
    return render_template_string(
        DASHBOARD_TEMPLATE,
        config=CONFIG,
        stats=stats,
        files=list(PROJECT_STATE['codebase']['files'].keys()),
        design_system=PROJECT_STATE['design_system'],
        messages=PROJECT_STATE['message_bus'],
        last_update=PROJECT_STATE.get('last_update'),
    )


@app.route('/files/<path:file_path>')
def view_file(file_path: str):
    """View a specific file from the generated codebase."""
    content = PROJECT_STATE['codebase']['files'].get(file_path)
    
    if content is None:
        return jsonify({
            'error': 'File not found',
            'file_path': file_path,
            'available_files': list(PROJECT_STATE['codebase']['files'].keys())
        }), 404
    
    return render_template_string(
        FILE_VIEWER_TEMPLATE,
        file_path=file_path,
        content=content,
    )


@app.route('/api/state')
def api_state():
    """Return the complete project state as JSON."""
    return jsonify(PROJECT_STATE)


@app.route('/api/files')
def api_files():
    """Return a list of all generated files with their content."""
    return jsonify({
        'files': PROJECT_STATE['codebase']['files'],
        'count': len(PROJECT_STATE['codebase']['files']),
    })


@app.route('/api/run-orchestrator', methods=['POST'])
def run_orchestrator():
    """Run the aurora orchestrator to generate new files."""
    try:
        # Initialize orchestrator with faster settings for web usage
        settings = SimulationSettings()
        settings.api_latency_seconds = 0.5  # Faster for web
        settings.loop_pause_seconds = 0.5
        
        orchestrator = AuroraOrchestrator(settings)
        orchestrator.generate_initial_tasks()
        orchestrator.main_loop()
        persist_final_state()
        
        return jsonify({
            'success': True,
            'message': 'Orchestrator completed successfully',
            'stats': {
                'completed': len(PROJECT_STATE['tasks']['completed']),
                'files': len(PROJECT_STATE['codebase']['files']),
                'messages': len(PROJECT_STATE['message_bus']),
            }
        })
    except Exception as e:
        return jsonify({
            'success': False,
            'error': str(e)
        }), 500


def main(host: str = '0.0.0.0', port: int = 5000, debug: bool = False) -> None:
    """Start the Flask web server.
    
    Args:
        host: Host address to bind to (default: 0.0.0.0)
        port: Port number to listen on (default: 5000)
        debug: Enable debug mode (default: False)
    """
    print("\n" + "=" * 70)
    print("🚀 A.U.R.O.R.A. Flask Web Server")
    print("=" * 70)
    print(f"Server starting on http://{host}:{port}")
    print("\nAvailable endpoints:")
    print(f"  • Dashboard:    http://localhost:{port}/")
    print(f"  • API State:    http://localhost:{port}/api/state")
    print(f"  • API Files:    http://localhost:{port}/api/files")
    print(f"  • View File:    http://localhost:{port}/files/<path>")
    print("\nPress Ctrl+C to stop the server")
    print("=" * 70 + "\n")
    
    app.run(host=host, port=port, debug=debug)


if __name__ == '__main__':
    # Check if orchestrator has been run, if not run it first
    if not PROJECT_STATE['codebase']['files']:
        print("No files in PROJECT_STATE. Running orchestrator first...")
        orchestrator = AuroraOrchestrator()
        orchestrator.generate_initial_tasks()
        orchestrator.main_loop()
        persist_final_state()
        print("\nOrchestrator completed. Starting web server...\n")
    
    # Start the Flask server
    main(
        host=os.getenv('FLASK_HOST', '0.0.0.0'),
        port=int(os.getenv('FLASK_PORT', 5000)),
        debug=os.getenv('FLASK_DEBUG', 'False').lower() == 'true',
    )
